spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
#为实体类取别名 映射类所在包名
  type-aliases-package: com.example.dao
  mapper-locations: /mappers/CityMapper.xml

